#!/bin/bash

# Copyright (C) 2009  Ericsson AB
#	Author: Bjorn Runaker <bjorn.runaker@ericsson.com>
#           Torgny Johansson <torgny.johansson@ericsson.com>

TERM_CMD=echo
CONTROL_DEV=/dev/ttyACM1

$TERM_CMD "AT*E2RESET" > $CONTROL_DEV 

